const tg = window.Telegram?.WebApp;
if (tg) { tg.ready(); tg.expand(); }

const roadmap = [
  {id:'w1', n:1, level:'Foundation', title:'Компьютерная база + Linux', desc:'ОС, файловая система, users/groups, permissions, процессы, сервисы, CLI.', theory:['CPU, RAM, SSD/HDD, BIOS/UEFI, процесс, поток, память, файл, программа, сервис.','Linux filesystem: /home, /etc, /var, /tmp, /proc.','Users/groups, sudo, permissions, processes и signals.','CLI: pwd, ls, cd, cp, mv, rm, mkdir, cat, less, grep, find, chmod, chown, ps, top, kill, systemctl, journalctl.'], practice:['Установить Linux VM.','Создать 2 пользователей и группу; настроить права.','Запустить/остановить сервис, найти процесс и PID.','Найти событие в логах через journalctl/grep.']},
  {id:'w2', n:2, level:'Foundation', title:'Windows + PowerShell', desc:'Процессы, службы, NTFS, Registry, Event Viewer, Defender, PowerShell.', theory:['Процессы, службы, пользователи, группы, NTFS, Registry, Event Viewer.','UAC, Firewall, Defender, права доступа.','PowerShell: Get-Process, Get-Service, Get-WinEvent, Get-ChildItem, Select-String.'], practice:['Создать пользователя и группу.','Найти процесс и службу.','Посмотреть события входа в Event Viewer.','Написать 5–10 простых PowerShell-команд.']},
  {id:'w3', n:3, level:'Foundation', title:'Сети: фундамент', desc:'OSI, TCP/IP, IPv4, subnetting, ARP, DHCP, NAT, TCP/UDP.', theory:['OSI и TCP/IP; Ethernet, MAC, IP, ARP.','IPv4, subnet, gateway, broadcast, DHCP, NAT.','TCP vs UDP, ports, sockets, connection.'], practice:['Разобрать 192.168.1.0/24, /25, /26, /27, /28.','Использовать ping, ipconfig/ifconfig, ip/route.','Объяснить, как ПК находит gateway и что делает ARP.']},
  {id:'w4', n:4, level:'Foundation', title:'TCP/IP + DNS + HTTP + Wireshark', desc:'TCP handshake, DNS, HTTP/HTTPS, TLS и анализ трафика.', theory:['TCP handshake, retransmission, ports.','DNS, DHCP, ICMP.','HTTP/HTTPS, request/response, headers, status codes.','TLS на уровне понимания.'], practice:['Поймать DNS-запрос в Wireshark.','Найти TCP handshake.','Разобрать HTTP request/response.','Использовать nslookup/dig, curl, traceroute/tracert.']},
  {id:'w5', n:5, level:'Foundation', title:'Python', desc:'Основы Python и автоматизация небольших security-задач.', theory:['Переменные, типы, условия, циклы, функции.','list/dict/set/tuple, exceptions, modules.','Файлы, JSON, regex, requests, socket, subprocess.'], practice:['Написать IP/port checker для своей лаборатории.','Прочитать лог и посчитать типы событий.','Сделать запрос к тестовому API и разобрать JSON.']},
  {id:'w6', n:6, level:'Foundation', title:'SQL + Web', desc:'SQL, HTTP, HTML, JS basics, cookies, sessions, REST API.', theory:['SELECT, INSERT, UPDATE, DELETE, WHERE, JOIN, GROUP BY, ORDER BY.','Primary/foreign key, relations, indexes.','HTML basics, JavaScript basics, HTTP, cookies, sessions, REST API, JSON.'], practice:['Создать небольшую БД и выполнить CRUD.','Разобрать запрос браузера в DevTools.','Отправить GET/POST через curl или Postman.','Объяснить authentication vs authorization.']},
  {id:'w7', n:7, level:'Security Core', title:'Основы информационной безопасности', desc:'CIA, threat/vulnerability/risk/exploit, controls и defense in depth.', theory:['CIA Triad.','Asset, threat, vulnerability, exploit, risk, control.','Attack surface, least privilege, defense in depth.'], practice:['Для 5 сценариев определить asset → threat → vulnerability → impact → control.']},
  {id:'w8', n:8, level:'Security Core', title:'Криптография', desc:'Hash, encryption, AES/RSA/ECC, signatures, PKI и TLS.', theory:['Hash vs encryption.','SHA-256/SHA-3, collision и password hashing.','Symmetric/asymmetric: AES, RSA, ECC.','Digital signatures, certificates, PKI, TLS.'], practice:['Разобрать путь HTTPS: certificate → key exchange → encrypted traffic.','Объяснить, почему пароль нельзя хранить просто как SHA-256.']},
  {id:'w9', n:9, level:'Security Core', title:'Authentication & Authorization', desc:'Пароли, MFA, sessions, cookies, tokens, JWT, OAuth/OIDC, RBAC.', theory:['Passwords, MFA, session, cookie, token.','JWT, OAuth 2.0, OpenID Connect.','RBAC и least privilege.','Common auth/session mistakes.'], practice:['Составить карту авторизации учебного веб-приложения.']},
  {id:'w10', n:10, level:'Security Core', title:'Network & System Security', desc:'Firewall, IDS/IPS, VPN, segmentation, hardening, logging.', theory:['Firewall, IDS/IPS, VPN, segmentation.','Endpoint security, patching, hardening.','Backups, logging, monitoring.','Basic threat modeling.'], practice:['Нарисовать схему лаборатории и отметить trust boundaries, сервисы и защиты.']},
  {id:'w11', n:11, level:'Web Security', title:'Burp + HTTP', desc:'Burp Proxy, Repeater, Intruder, requests, responses и модель браузера.', theory:['Burp Proxy, Repeater, Intruder.','Requests, responses, headers, cookies, parameters.','Same-Origin Policy.'], practice:['Перехватить запрос в учебной лаборатории, изменить параметр и проверить результат.']},
  {id:'w12', n:12, level:'Web Security', title:'Injection', desc:'SQLi, Command Injection, Path Traversal и File Upload.', theory:['SQL Injection.','Command Injection.','Path Traversal.','File upload vulnerabilities.'], practice:['Пройти учебные labs. Для каждой: причина → условие → impact → mitigation.']},
  {id:'w13', n:13, level:'Web Security', title:'XSS + CSRF + Access Control', desc:'XSS, CSRF, IDOR/Broken Access Control и session weaknesses.', theory:['Stored/Reflected/DOM XSS.','CSRF.','IDOR/Broken Access Control.','Session weaknesses.'], practice:['Пройти beginner labs и записать, как исправить каждую проблему.']},
  {id:'w14', n:14, level:'Web Security', title:'SSRF + API Security + OWASP', desc:'SSRF, API auth, rate limiting и OWASP Top 10.', theory:['SSRF.','API authentication/authorization.','Rate limiting.','OWASP Top 10 как карта тем.'], practice:['Составить свою шпаргалку OWASP и пройти beginner labs.']},
  {id:'w15', n:15, level:'AD & Pentest', title:'Windows Internals для ИБ', desc:'Processes, services, tokens, privileges, logs, Sysmon и PowerShell.', theory:['Processes, services, tokens, privileges.','Windows Event Logs, Sysmon.','PowerShell и удалённое управление.','NTFS permissions.'], practice:['Создать безопасный сценарий в lab и найти его следы в логах.']},
  {id:'w16', n:16, level:'AD & Pentest', title:'Active Directory', desc:'Domain, DC, LDAP, Kerberos, NTLM, users, groups, OU, GPO, SMB.', theory:['Domain, Domain Controller, LDAP, Kerberos, NTLM.','Users, groups, OU, GPO.','SMB, DNS и AD-зависимости.'], practice:['Собрать учебный AD lab с Windows Server + client, если позволяет ПК.']},
  {id:'w17', n:17, level:'AD & Pentest', title:'AD Security', desc:'Kerberoasting, AS-REP Roasting, Pass-the-Hash/Ticket, ACL abuse.', theory:['Kerberoasting, AS-REP Roasting.','Pass-the-Hash / Pass-the-Ticket.','ACL abuse, lateral movement.','Credential hygiene и hardening.'], practice:['Только lab/CTF: prerequisites, detection и mitigation для каждой техники.']},
  {id:'w18', n:18, level:'AD & Pentest', title:'Основы Pentest Workflow', desc:'Recon → enumeration → discovery → exploitation → escalation → report.', theory:['Recon, enumeration, vulnerability discovery, exploitation.','Nmap.','Linux/Windows privilege escalation в lab.'], practice:['Решить 2–3 beginner machines и написать отчёт.']},
  {id:'w19', n:19, level:'Blue Team', title:'Логи и расследование', desc:'Windows/Linux/Web logs, IOC и timeline investigation.', theory:['Windows Event Logs.','Linux logs.','Web server logs.','IOC и timeline.'], practice:['Сгенерировать безопасные события и найти их в логах.']},
  {id:'w20', n:20, level:'Blue Team', title:'SIEM', desc:'Parsing, fields, correlation, alerts. Wazuh/Elastic/Splunk.', theory:['Что такое SIEM.','Parsing, fields, correlation, alerts.','Выбрать Wazuh, Elastic или Splunk.'], practice:['Настроить базовый сбор логов и 2 простых detection rules.']},
  {id:'w21', n:21, level:'Blue Team', title:'MITRE ATT&CK', desc:'Tactics, Techniques, Procedures и цепочки атак.', theory:['Tactics, Techniques, Procedures.','Initial Access, Execution, Persistence, Privilege Escalation, Lateral Movement, Credential Access, Discovery.'], practice:['Для учебного инцидента построить ATT&CK chain и точки detection.']},
  {id:'w22', n:22, level:'Blue Team', title:'Incident Response', desc:'Detection, analysis, containment, eradication, recovery и отчёт.', theory:['Preparation, detection, analysis, containment, eradication, recovery.','False positive vs true positive.','Evidence и документация.'], practice:['Разобрать учебный alert и написать incident report.']},
  {id:'w23', n:23, level:'Practice', title:'CTF Fundamentals', desc:'Beginner CTF: Linux, networking, web, crypto.', theory:['Выбрать beginner-платформу.','Не копировать write-up до собственной попытки.'], practice:['Решить 5–10 небольших задач.']},
  {id:'w24', n:24, level:'Practice', title:'Мини-проект: Python', desc:'Небольшой security utility + README.', theory:['Python + networking/security.'], practice:['Написать log analyzer, HTTP checker, hash checker или другой utility для своей lab.']},
  {id:'w25', n:25, level:'Practice', title:'Мини-проект: Web или SOC', desc:'Выбрать AppSec или Blue Team и сделать законченный мини-проект.', theory:['Web security report или SOC/SIEM mini lab.'], practice:['Оформить README, screenshots и выводы.']},
  {id:'w26', n:26, level:'Practice', title:'Итоговый проект', desc:'Собрать знания в один безопасный лабораторный сценарий.', theory:['Lab → reconnaissance → analysis → findings → detection/mitigation → report.'], practice:['Сделать полный write-up и список следующих тем для углубления.']}
];

const state = { route:'home', selected:null, query:'', notes:[], taskState:{}, customTasks:{} };
const KEY='cyberroadmap_state_v1';

function loadLocal(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');Object.assign(state,x);state.route='home';}catch{}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify({taskState:state.taskState,notes:state.notes,customTasks:state.customTasks}));}
function cloudGet(key){return new Promise(resolve=>{if(!tg?.CloudStorage)return resolve(null);tg.CloudStorage.getItem(key,(e,v)=>resolve(e?null:v));})}
function cloudSet(key,value){return new Promise(resolve=>{if(!tg?.CloudStorage)return resolve(false);tg.CloudStorage.setItem(key,value,e=>resolve(!e));})}
async function load(){loadLocal(); const c=await cloudGet('roadmap'); if(c){try{Object.assign(state,JSON.parse(c));}catch{}}}
async function persist(){saveLocal(); await cloudSet('roadmap',JSON.stringify({taskState:state.taskState,notes:state.notes,customTasks:state.customTasks}));}
function h(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function taskId(w,i,type){return `${w.id}:${type}:${i}`}
function getTasks(w,type){const base=type==='theory'?w.theory:w.practice; const extra=state.customTasks[`extras:${w.id}:${type}`]||[]; return [...base,...extra].map((t,i)=>state.customTasks[taskId(w,i,type)]?.text||t)}
function isDone(w,i,type){return !!state.taskState[taskId(w,i,type)]}
function weekStats(w){const a=getTasks(w,'theory').length+getTasks(w,'practice').length; let d=0; ['theory','practice'].forEach(type=>getTasks(w,type).forEach((_,i)=>{if(isDone(w,i,type))d++}));return {d,a,p:a?Math.round(d/a*100):0}}
function allStats(){let d=0,a=0;roadmap.forEach(w=>{const s=weekStats(w);d+=s.d;a+=s.a});return {d,a,p:a?Math.round(d/a*100):0}}
function levelStats(level){const ws=roadmap.filter(w=>w.level===level);let d=0,a=0;ws.forEach(w=>{const s=weekStats(w);d+=s.d;a+=s.a});return {d,a,p:a?Math.round(d/a*100):0}}
function currentWeek(){return roadmap.find(w=>weekStats(w).p<100)||roadmap[roadmap.length-1]}
function render(){
  const main=document.getElementById('main');
  document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));
  document.getElementById('backBtn').classList.toggle('hidden',!!state.selected);
  if(state.selected){renderDetail(main,state.selected);return}
  if(state.route==='roadmap')renderRoadmap(main); else if(state.route==='today')renderToday(main); else if(state.route==='notes')renderNotes(main); else renderHome(main);
}
function renderHome(main){const s=allStats(),cw=currentWeek(),cs=weekStats(cw), doneToday=Object.keys(state.taskState).length;
main.innerHTML=`<section class="hero"><div class="eyebrow">PERSONAL LEARNING SYSTEM</div><h1>Твой путь в<br>Cybersecurity.</h1><p>От восстановления базы до уверенного junior. Маленькие шаги каждый день, реальные лаборатории и понятный прогресс.</p></section>
<div class="grid"><div class="card stats"><div class="progress-row"><div><div class="muted" style="font-size:12px">ОБЩИЙ ПРОГРЕСС</div><div class="progress-value">${s.p}%</div></div><div style="text-align:right"><b>${s.d} / ${s.a}</b><div class="muted" style="font-size:11px">задач выполнено</div></div></div><div class="bar"><i style="width:${s.p}%"></i></div><div class="stats-foot"><span>Текущий этап: ${h(cw.level)}</span><span>Неделя ${cw.n} из 26</span></div></div>
<div class="card quick"><div class="qicon">🎯</div><b>Продолжить</b><span>Неделя ${cw.n}: ${h(cw.title)}</span><button class="link-btn" style="padding:9px 0" data-open-week="${cw.id}">Открыть →</button></div>
<div class="card quick"><div class="qicon">✓</div><b>Сегодня</b><span>${Math.min(5,cs.a-cs.d)} ближайших задач в текущей неделе</span><button class="link-btn" style="padding:9px 0" data-route="today">К задачам →</button></div>
<div class="card quick"><div class="qicon">✎</div><b>Заметки</b><span>${state.notes.length} личных заметок</span><button class="link-btn" style="padding:9px 0" data-route="notes">Открыть →</button></div></div>
<div class="section-title"><h2>Фокус недели</h2><button class="link-btn" data-route="roadmap">Весь roadmap</button></div>
<div class="grid"><div class="card focus"><div class="focus-top"><span class="tag">Неделя ${cw.n} · ${h(cw.level)}</span><span class="muted">${cs.p}%</span></div><h3>${h(cw.title)}</h3><p>${h(cw.desc)}</p><button class="primary" data-open-week="${cw.id}">Продолжить</button></div><div class="card task-card"><div class="task-head"><h3>Ближайшие задачи</h3><span class="muted">${cs.d}/${cs.a}</span></div><div class="task-list">${nextTasks(cw,5).map(x=>taskHtml(cw,x.i,x.type,x.text)).join('')||'<div class="empty">Неделя завершена 🎉</div>'}</div></div></div>
<div class="section-title"><h2>Уровни</h2></div><div class="grid">${['Foundation','Security Core','Web Security','AD & Pentest','Blue Team','Practice'].map(levelCard).join('')}</div>`;
wire();}
function levelCard(level){const s=levelStats(level);return `<div class="card quick"><div class="tag">${h(level)}</div><div style="margin-top:13px;font-size:20px;font-weight:850">${s.p}%</div><div class="bar" style="margin:8px 0"><i style="width:${s.p}%"></i></div><span>${s.d}/${s.a} задач</span></div>`}
function nextTasks(w,n){const out=[];for(const type of ['theory','practice']){getTasks(w,type).forEach((text,i)=>{if(!isDone(w,i,type)&&out.length<n)out.push({i,type,text})})}return out}
function taskHtml(w,i,type,text){return `<label class="task ${isDone(w,i,type)?'done':''}"><input type="checkbox" data-task="${taskId(w,i,type)}" ${isDone(w,i,type)?'checked':''}><span>${h(text)}</span></label>`}
function renderRoadmap(main){const levels=[...new Set(roadmap.map(w=>w.level))];main.innerHTML=`<section class="hero"><div class="eyebrow">ROADMAP</div><h1>26 недель.<br>Одна система.</h1><p>Проходи последовательно, но не бойся возвращаться к темам. Открытые недели можно редактировать и дополнять своими задачами.</p></section><input class="search" id="search" placeholder="Поиск по темам…" value="${h(state.query)}"><div id="weeks">${levels.map(level=>`<div class="section-title"><h2>${h(level)}</h2><span class="muted">${levelStats(level).p}%</span></div><div class="week-list">${roadmap.filter(w=>w.level===level).filter(w=>(w.title+' '+w.desc).toLowerCase().includes(state.query.toLowerCase())).map(weekHtml).join('')}</div>`).join('')}</div>`;wire();document.getElementById('search').addEventListener('input',e=>{state.query=e.target.value;renderRoadmap(document.getElementById('main'));});}
function weekHtml(w){const s=weekStats(w);return `<button class="card week" data-open-week="${w.id}"><div class="week-badge">${w.n}</div><div class="week-main"><h3>${h(w.title)}</h3><p>${h(w.desc)}</p></div><div class="week-progress"><small>${s.d}/${s.a}</small><div class="bar"><i style="width:${s.p}%"></i></div></div><div class="chev">›</div></button>`}
function renderDetail(main,id){const w=roadmap.find(x=>x.id===id);if(!w)return;const s=weekStats(w);main.innerHTML=`<section class="detail-head"><span class="tag">Неделя ${w.n} · ${h(w.level)}</span><h1>${h(w.title)}</h1><p>${h(w.desc)}</p></section><div class="card detail-card"><div class="progress-row"><div><b>Прогресс недели</b></div><strong>${s.p}%</strong></div><div class="bar"><i style="width:${s.p}%"></i></div></div>${detailSection(w,'Теория','theory')} ${detailSection(w,'Практика','practice')}<div class="card detail-card"><h2>📝 Моя заметка по неделе</h2><textarea class="note-box" id="weekNote" placeholder="Что понял? Что осталось непонятным? Что повторить?">${h(state.notes.find(n=>n.id===w.id)?.text||'')}</textarea><div class="modal-actions"><button class="primary" id="saveNote">Сохранить заметку</button></div></div><div class="card detail-card"><h2>✏️ Редактирование</h2><p class="muted" style="font-size:12px;line-height:1.5">Можно добавлять свои задачи и менять текст существующих. Базовый roadmap остаётся сохранённым как шаблон.</p><button class="ghost" id="addTask">+ Добавить свою задачу</button></div>`;wire();document.getElementById('saveNote').onclick=async()=>{const text=document.getElementById('weekNote').value;state.notes=state.notes.filter(n=>n.id!==w.id);if(text.trim())state.notes.push({id:w.id,text});await persist();toast('Заметка сохранена');};document.getElementById('addTask').onclick=()=>openTaskModal(w);}
function detailSection(w,title,type){const tasks=getTasks(w,type);return `<div class="card detail-card"><h2>${title}</h2><div class="checklist">${tasks.map((text,i)=>`<div class="check-row ${isDone(w,i,type)?'done':''}"><input type="checkbox" data-task="${taskId(w,i,type)}" ${isDone(w,i,type)?'checked':''}><span class="check-text">${h(text)}</span><button class="edit-mini" data-edit-task="${taskId(w,i,type)}">✎</button></div>`).join('')}</div></div>`}
function renderToday(main){const w=currentWeek(), items=nextTasks(w,8);main.innerHTML=`<section class="hero"><div class="eyebrow">TODAY</div><h1>На сегодня.</h1><p>Не пытайся сделать всё. Выбери несколько задач и закрой их качественно.</p></section><div class="card detail-card"><div class="progress-row"><div><b>Неделя ${w.n}: ${h(w.title)}</b><div class="muted" style="font-size:11px;margin-top:4px">${weekStats(w).d}/${weekStats(w).a} выполнено</div></div><span class="tag">${weekStats(w).p}%</span></div></div><div class="week-list">${items.map(x=>`<div class="card today-item"><div class="today-icon">${x.type==='theory'?'📖':'🧪'}</div><div class="today-main"><b>${h(x.text)}</b><small>${x.type==='theory'?'Теория':'Практика'} · Неделя ${w.n}</small></div><span class="pill">TODO</span><input type="checkbox" data-task="${taskId(w,x.i,x.type)}" style="width:20px;height:20px;accent-color:var(--green)"></div>`).join('')}</div>`;wire();}
function renderNotes(main){main.innerHTML=`<section class="hero"><div class="eyebrow">KNOWLEDGE BASE</div><h1>Твои заметки.</h1><p>Фиксируй непонятные моменты, команды, ошибки и идеи. Это часть обучения, а не отдельная обязанность.</p></section><button class="primary" id="newNote">+ Новая заметка</button><div class="notes-grid" style="margin-top:14px">${state.notes.map(n=>{const w=roadmap.find(x=>x.id===n.id);return `<article class="card note-item"><h3>${h(w?.title||'Личная заметка')}</h3><p>${h(n.text)}</p><div style="margin-top:10px"><button class="edit-mini" data-note-edit="${h(n.id)}">✎ Редактировать</button></div></article>`}).join('')||'<div class="empty">Пока пусто. Добавь первую заметку.</div>'}</div>`;wire();document.getElementById('newNote').onclick=()=>openNoteModal();}
function wire(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;state.selected=null;render();});document.querySelectorAll('[data-open-week]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.openWeek;render();});document.querySelectorAll('[data-task]').forEach(el=>el.onchange=async()=>{state.taskState[el.dataset.task]=el.checked;await persist();if(tg?.HapticFeedback)tg.HapticFeedback.impactOccurred('light');render();});document.querySelectorAll('[data-edit-task]').forEach(b=>b.onclick=()=>openEditTask(b.dataset.editTask));document.querySelectorAll('[data-note-edit]').forEach(b=>b.onclick=()=>openNoteModal(b.dataset.noteEdit));}
function openTaskModal(w){openModal('Добавить задачу',`<div class="field"><label>Текст задачи</label><input id="newTaskText" placeholder="Например: решить 10 subnetting задач"></div><div class="field"><label>Раздел</label><select id="newTaskType" style="width:100%;padding:11px;background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:12px"><option value="practice">Практика</option><option value="theory">Теория</option></select></div><div class="modal-actions"><button class="ghost" id="cancel">Отмена</button><button class="primary" id="save">Добавить</button></div>`);document.getElementById('save').onclick=async()=>{const text=document.getElementById('newTaskText').value.trim(),type=document.getElementById('newTaskType').value;if(!text)return;const key=`extras:${w.id}:${type}`;state.customTasks[key]=[...(state.customTasks[key]||[]),text];closeModal();await persist();render();};}
function openEditTask(key){const [wid,type,i]=key.split(':');const w=roadmap.find(x=>x.id===wid);if(!w)return;const old=getTasks(w,type)[Number(i)]||'';openModal('Редактировать задачу',`<div class="field"><label>Текст</label><textarea id="editText">${h(old)}</textarea></div><div class="modal-actions"><button class="ghost" id="cancel">Отмена</button><button class="primary" id="save">Сохранить</button></div>`);document.getElementById('save').onclick=async()=>{const text=document.getElementById('editText').value.trim();if(!text)return;state.customTasks[key]={text};closeModal();await persist();render();};}
function openNoteModal(id){const existing=state.notes.find(n=>n.id===id);openModal('Новая заметка',`<div class="field"><label>Заголовок</label><input id="noteTitle" value="${h(existing?.title||'Личная заметка')}" placeholder="Название"></div><div class="field"><label>Текст</label><textarea id="noteText">${h(existing?.text||'')}</textarea></div><div class="modal-actions"><button class="ghost" id="cancel">Отмена</button><button class="primary" id="save">Сохранить</button></div>`);document.getElementById('save').onclick=async()=>{const text=document.getElementById('noteText').value.trim();if(!text)return;state.notes=state.notes.filter(n=>n.id!==id);state.notes.push({id:id||`note-${Date.now()}`,title:document.getElementById('noteTitle').value.trim(),text});closeModal();await persist();render();};}
function openModal(title,body){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modal').classList.remove('hidden');document.getElementById('modal').querySelectorAll('#cancel').forEach(b=>b.onclick=closeModal);}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function toast(text){const t=document.createElement('div');t.textContent=text;t.style.cssText='position:fixed;left:50%;bottom:90px;transform:translateX(-50%);z-index:80;background:#1b2230;color:white;padding:10px 14px;border:1px solid #303a4e;border-radius:12px;font-size:12px;box-shadow:0 12px 35px #0008';document.body.appendChild(t);setTimeout(()=>t.remove(),1500)}

document.getElementById('backBtn').onclick=()=>{state.selected=null;render()};
document.getElementById('settingsBtn').onclick=()=>openModal('Настройки',`<div class="field"><label>Хранилище</label><div class="muted" style="font-size:12px;line-height:1.5">${tg?.CloudStorage?'Telegram CloudStorage включён.':'Локальное хранилище браузера. Открой приложение внутри Telegram для облачной синхронизации.'}</div></div><div class="field"><label>Тема</label><div class="muted" style="font-size:12px">Интерфейс автоматически подстраивается под тему Telegram.</div></div><div class="modal-actions"><button class="ghost" id="reset">Сбросить прогресс</button></div>`);setTimeout(()=>{document.getElementById('reset')?.addEventListener('click',async()=>{if(confirm('Сбросить весь прогресс и заметки?')){state.taskState={};state.notes=[];state.customTasks={};await persist();closeModal();render();}})},0);
document.getElementById('modalClose').onclick=closeModal;document.querySelector('.modal-backdrop').onclick=closeModal;

(async()=>{await load();render();})();
