
const TG = window.Telegram?.WebApp;
const SYNC_URL = "https://odkbzwztkmxnyfduuqbf.supabase.co/functions/v1/telegram-sync";
if(TG){TG.ready();TG.expand();try{TG.setHeaderColor("#080c13");TG.setBackgroundColor("#080c13")}catch(e){}}

const lessons = [
{title:"Linux & OS",track:"Foundation",icon:"🐧",desc:"Файловая система, права, процессы, пользователи и Bash.",theory:["Linux — семейство Unix-подобных ОС; для ИБ важно уверенно работать с CLI, процессами, сетью, журналами и правами.","Освой /etc, /var, /home, /tmp, /proc; различай абсолютные и относительные пути.","Права rwx применяются к owner/group/others. chmod меняет mode, chown — владельца.","Процессы можно искать через ps/top, управлять сигналами kill, а службы — через systemctl.","Bash нужен для автоматизации: переменные, пайпы |, перенаправления > и >>, grep, find, awk, sed."],practice:["Создать пользователя и группу в лабораторной VM","Настроить права на каталог с chmod/chown","Найти процесс и безопасно завершить его","Написать Bash-скрипт, который ищет ошибки в логах"],resources:[["Linux Foundation — Introduction to Linux","https://training.linuxfoundation.org/training/introduction-to-linux/"],["Linux man-pages","https://man7.org/linux/man-pages/"],["OverTheWire Bandit","https://overthewire.org/wargames/bandit/"]],quiz:[["Какая команда показывает текущий каталог?","pwd",["pwd","cd","ls","whoami"]],["Что делает chmod?","Изменяет права доступа",["Меняет владельца","Изменяет права доступа","Удаляет файл","Показывает процессы"]]]},
{title:"Networking",track:"Foundation",icon:"🌐",desc:"TCP/IP, DNS, DHCP, маршрутизация, порты и сокеты.",theory:["Разделяй IP-адрес хоста и порт приложения. TCP обеспечивает соединение и порядок доставки; UDP — лёгкую передачу без гарантии доставки.","DNS сопоставляет имена и IP. DHCP выдаёт сетевые параметры. ARP связывает IPv4-адрес с MAC в локальной сети.","Понимай CIDR: /24 означает 24 бита сети. Умей определить сеть, broadcast и диапазон адресов.","Изучи TCP three-way handshake, состояния соединений и роль firewall.","Для ИБ критично уметь читать трафик и связывать DNS, IP, порт, протокол и процесс."],practice:["Разобрать ipconfig/ip addr и route в своей системе","Снять безопасный трафик своей лаборатории в Wireshark","Разобрать DNS-запрос и TCP handshake","Составить таблицу портов популярных сервисов"],resources:[["Wireshark User Guide","https://www.wireshark.org/docs/wsug_html/"],["Cloudflare Learning Center — Networking","https://www.cloudflare.com/learning/network-layer/"],["MDN — HTTP overview","https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview"]],quiz:[["Какой протокол обычно используется для надёжной передачи с установлением соединения?","TCP",["UDP","TCP","ARP","DNS"]],["Что делает DNS?","Сопоставляет имена и адреса",["Шифрует трафик","Сопоставляет имена и адреса","Выдаёт MAC","Фильтрует порты"]]]},
{title:"Python",track:"Foundation",icon:"🐍",desc:"Синтаксис, функции, файлы, HTTP и автоматизация.",theory:["Тебе не нужен Python ради самого Python: цель — автоматизация ИБ-задач и создание небольших инструментов.","Освой типы данных, условия, циклы, функции, исключения, модули и виртуальные окружения.","Работа с файлами: pathlib/open; JSON и CSV; регулярные выражения — только после уверенной базы.","Для HTTP изучи requests/urllib, статус-коды, заголовки, cookies и безопасную обработку ошибок.","Не запускай непроверенный код и не тестируй чужие системы без разрешения."],practice:["Написать анализатор access.log","Сделать скрипт, который проверяет HTTP status codes в своей лаборатории","Разобрать JSON-ответ API","Сделать CLI-инструмент с argparse"],resources:[["Python Documentation","https://docs.python.org/3/"],["Python Tutorial","https://docs.python.org/3/tutorial/"],["Requests Documentation","https://requests.readthedocs.io/"]],quiz:[["Что используется для обработки исключений?","try/except",["if/else","try/except","for/in","import"]],["Что обычно возвращает HTTP GET?","Ответ сервера",["Только DNS","Ответ сервера","MAC-адрес","SSH-ключ"]]]},
{title:"Git & GitHub",track:"Foundation",icon:"🌿",desc:"Коммиты, ветки, README и портфолио.",theory:["Git фиксирует историю изменений. Репозиторий — проект и его история; commit — снимок изменений.","Изучи clone, status, add, commit, log, branch, switch/checkout, merge и pull/push.","Никогда не коммить секреты: токены, приватные ключи, .env и пароли. Используй .gitignore.","GitHub-портфолио для ИБ должно показывать лаборатории, write-up, скрипты и документацию."],practice:["Создать отдельный репозиторий для учебных лабораторий","Сделать ветку feature и merge","Оформить README с целью, окружением и результатами","Проверить репозиторий на случайно добавленные секреты"],resources:[["Git Documentation","https://git-scm.com/doc"],["GitHub Skills","https://skills.github.com/"],["GitHub Docs","https://docs.github.com/"]],quiz:[["Как сохранить изменения в истории Git?","commit",["push","commit","clone","fetch"]],["Где хранить секреты проекта?","В защищённом secret storage, не в репозитории",["В README","В public repo","В secret storage","В названии файла"]]]},
{title:"Web fundamentals",track:"Foundation",icon:"🌍",desc:"HTTP, cookies, sessions и браузерная модель.",theory:["HTTP — протокол запросов и ответов. Изучи methods, status codes, headers, body и content types.","Cookies могут хранить идентификатор сессии. Secure запрещает отправку по HTTP, HttpOnly ограничивает JS-доступ, SameSite влияет на cross-site отправку.","Аутентификация отвечает на вопрос «кто ты», авторизация — «что тебе разрешено».","Понимай origin, same-origin policy, CORS и базовую модель браузера."],practice:["Посмотреть HTTP-запросы DevTools","Разобрать cookie-флаги на тестовом сайте","Сравнить 200/301/400/401/403/404/500","Найти в локальной лаборатории, где хранится session identifier"],resources:[["MDN HTTP","https://developer.mozilla.org/en-US/docs/Web/HTTP"],["MDN Cookies","https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies"],["PortSwigger Web Security Academy","https://portswigger.net/web-security"]],quiz:[["401 обычно означает…","Требуется аутентификация",["Forbidden","Требуется аутентификация","Not Found","Server Error"]],["HttpOnly cookie в первую очередь снижает риск…","доступа к cookie из JavaScript",["DNS spoofing","доступа к cookie из JavaScript","DDoS","ARP poisoning"]]]},
{title:"SQL",track:"Foundation",icon:"🗃️",desc:"Запросы, joins, индексы и транзакции.",theory:["SQL описывает запросы к реляционным данным. Освой SELECT, WHERE, ORDER BY, GROUP BY, JOIN, INSERT, UPDATE, DELETE.","Первичный ключ идентифицирует строку; foreign key связывает таблицы.","Индексы ускоряют чтение, но увеличивают стоимость записи и место.","Транзакции позволяют группировать изменения; ACID — фундамент надёжности.","Для ИБ обязательно понимать parameterized queries и почему конкатенация пользовательского ввода опасна."],practice:["Создать маленькую БД пользователей и ролей","Написать 10 SELECT с фильтрами и JOIN","Посмотреть план запроса","Сделать безопасный parameterized query в Python"],resources:[["PostgreSQL Documentation","https://www.postgresql.org/docs/"],["OWASP SQL Injection Prevention","https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html"]],quiz:[["Что связывает строку с уникальным идентификатором?","Primary key",["Index","Primary key","View","Trigger"]],["Лучший базовый способ защиты от SQL injection в приложении?","Parameterized queries",["Удалить БД","Parameterized queries","Скрыть URL","Использовать GET"]]]},
{title:"Windows internals",track:"Foundation",icon:"🪟",desc:"Процессы, службы, Registry и Event Viewer.",theory:["Понимай процессы, threads, services, users, groups и Windows security model.","Registry содержит конфигурацию; Event Viewer — важный источник журналов.","Изучи PowerShell на уровне автоматизации: Get-Process, Get-Service, Get-WinEvent и работа с объектами.","Для ИБ важны события входа, создания процессов, изменений прав и сетевой активности."],practice:["Найти процессы и службы через PowerShell","Изучить Security log в тестовой Windows VM","Собрать события за выбранный период","Написать PowerShell-скрипт для поиска подозрительных событий"],resources:[["Microsoft Learn — Windows Security","https://learn.microsoft.com/windows/security/"],["Microsoft Learn — PowerShell","https://learn.microsoft.com/powershell/"],["Sysinternals","https://learn.microsoft.com/sysinternals/"]],quiz:[["Где смотреть системные журналы Windows?","Event Viewer",["Registry","Event Viewer","Task Scheduler","Explorer"]],["Команда PowerShell для процессов?","Get-Process",["Get-Service","Get-Process","Get-Event","Get-Net"]]]},
{title:"Auth & IAM",track:"Security Core",icon:"🔐",desc:"Пароли, MFA, сессии, RBAC и контроль доступа.",theory:["Authentication подтверждает личность, authorization определяет права.","Пароли должны храниться как медленные salted hashes; plaintext хранить нельзя.","MFA добавляет независимый фактор. Не все MFA одинаково устойчивы к фишингу.","RBAC выдаёт права по ролям. Least privilege означает минимально необходимые права.","Сессии должны иметь случайные идентификаторы, короткий срок жизни и безопасные cookie-флаги."],practice:["Составить матрицу ролей для учебного приложения","Разобрать password hashing vs encryption","Настроить MFA на собственных учебных аккаунтах","Найти примеры privilege escalation из-за плохой авторизации"],resources:[["OWASP Authentication Cheat Sheet","https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html"],["OWASP Authorization Cheat Sheet","https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html"],["NIST Digital Identity Guidelines","https://pages.nist.gov/800-63-4/"]],quiz:[["RBAC означает…","Role Based Access Control",["Risk Based Access Control","Role Based Access Control","Remote Backup Access Control","Random Based Access Control"]],["Что лучше для хранения паролей?","Salted password hashing",["Reversible encryption","Salted password hashing","Plaintext","Base64"]]]},
{title:"Cryptography",track:"Security Core",icon:"🔒",desc:"Хеширование, шифрование, подписи, PKI и TLS.",theory:["Hash — одностороннее преобразование фиксированного размера; encryption предназначено для обратимого восстановления при наличии ключа.","Symmetric crypto использует общий ключ; asymmetric — пару public/private keys.","Digital signature даёт проверку целостности и владения приватным ключом.","TLS защищает канал, а сертификаты связывают идентичность с публичным ключом через PKI.","Не изобретай криптографию: используй проверенные библиотеки и режимы."],practice:["Сравнить SHA-256 и AES на безопасных тестовых данных","Посмотреть сертификат HTTPS-сайта","Сгенерировать учебную пару ключей","Объяснить TLS handshake своими словами"],resources:[["NIST Cryptographic Standards","https://csrc.nist.gov/projects/cryptographic-standards-and-guidelines"],["MDN TLS","https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security"],["OpenSSL Documentation","https://docs.openssl.org/"]],quiz:[["Что обеспечивает hash?","Проверяемый отпечаток данных",["Обратимое шифрование","Проверяемый отпечаток данных","Маршрутизацию","Аутентификацию пользователя всегда"]],["Private key в цифровой подписи хранится…","у владельца",["у любого клиента","у владельца","в DNS","в HTTP header"]]]},
{title:"Threat modeling",track:"Security Core",icon:"🧠",desc:"Активы, угрозы, attack surface и STRIDE.",theory:["Threat modeling — системный способ заранее искать угрозы и выбирать меры защиты.","Начни с assets, trust boundaries, data flows и entry points.","STRIDE: Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege.","Приоритизируй угрозы по влиянию и вероятности, затем связывай их с mitigations."],practice:["Нарисовать DFD для учебного веб-приложения","Найти 10 потенциальных угроз","Разложить угрозы по STRIDE","Составить таблицу threat → impact → mitigation"],resources:[["Microsoft Threat Modeling Tool","https://learn.microsoft.com/azure/security/develop/threat-modeling-tool"],["OWASP Threat Modeling","https://owasp.org/www-community/Threat_Modeling"]],quiz:[["STRIDE используется для…","классификации угроз",["шифрования","классификации угроз","мониторинга CPU","управления Git"]]]},
{title:"Security architecture",track:"Security Core",icon:"🏗️",desc:"Defense in depth, сегментация и Zero Trust.",theory:["Defense in depth означает несколько независимых уровней защиты.","Network segmentation ограничивает blast radius компрометации.","Zero Trust исходит из принципа не доверять автоматически только потому, что пользователь внутри сети.","Security controls должны быть измеримыми: prevention, detection, response."],practice:["Спроектировать сегментацию небольшой компании","Нарисовать trust boundaries","Для каждого слоя указать prevention и detection control","Составить план восстановления после компрометации одного сегмента"],resources:[["NIST Zero Trust Architecture","https://csrc.nist.gov/publications/detail/sp/800-207/final"],["CISA Zero Trust Maturity Model","https://www.cisa.gov/resources-tools/resources/zero-trust-maturity-model"]],quiz:[["Главная идея Zero Trust?","Постоянно проверять доступ и контекст",["Доверять LAN","Постоянно проверять доступ и контекст","Отключить MFA","Запретить интернет"]]]},
{title:"Vulnerability management",track:"Security Core",icon:"🩹",desc:"CVE, CVSS, патчинг и приоритизация.",theory:["Vulnerability management — процесс обнаружения, оценки, исправления и повторной проверки уязвимостей.","CVE идентифицирует известную уязвимость; CVSS помогает оценивать техническую серьёзность.","Приоритет нельзя строить только на CVSS: учитывай экспозицию, наличие exploit, ценность актива и компенсирующие controls.","Хороший процесс заканчивается remediation и validation."],practice:["Найти CVE для используемого ПО","Разобрать CVSS vector на примере","Составить risk register из 10 находок","Проверить, что remediation действительно закрыла проблему"],resources:[["NVD","https://nvd.nist.gov/"],["FIRST CVSS","https://www.first.org/cvss/"],["CISA KEV Catalog","https://www.cisa.gov/known-exploited-vulnerabilities-catalog"]],quiz:[["CVE — это…","идентификатор известной уязвимости",["шифр","идентификатор известной уязвимости","лог","пароль"]]]},
{title:"OWASP Top 10",track:"Web Security",icon:"🕸️",desc:"Классы рисков веб-приложений и mitigations.",theory:["OWASP Top 10 — ориентир по наиболее критичным рискам веб-приложений; изучай не только названия, но и причины, признаки и защиту.","Связывай уязвимость с нарушением CIA, авторизации, валидации ввода или конфигурации.","Практикуйся только на собственных приложениях или специально разрешённых учебных лабораториях."],practice:["Пройти вводные labs PortSwigger","Для каждого класса записать cause → impact → mitigation","Сделать собственное уязвимое demo-приложение в локальной среде","Написать remediation checklist"],resources:[["OWASP Top 10","https://owasp.org/www-project-top-ten/"],["PortSwigger Academy","https://portswigger.net/web-security"]],quiz:[["OWASP Top 10 — это…","ориентир по ключевым рискам веб-приложений",["список паролей","ориентир по ключевым рискам веб-приложений","VPN","SIEM"]]]},
{title:"Burp Suite",track:"Web Security",icon:"🦋",desc:"Proxy, Repeater и безопасный workflow тестирования.",theory:["Burp Suite позволяет видеть и изменять HTTP(S) трафик тестового приложения.","Proxy — перехват, Repeater — ручное повторение запросов, Intruder — автоматизация тестов в разрешённой среде.","Сначала понять нормальный request/response, затем менять один параметр и наблюдать эффект.","Всегда используй scope и лаборатории, чтобы не затронуть чужие системы."],practice:["Настроить Burp с браузером для localhost","Перехватить login request своей лаборатории","Повторить запрос в Repeater","Составить короткий finding с evidence и remediation"],resources:[["PortSwigger Burp Documentation","https://portswigger.net/burp/documentation"],["PortSwigger Web Security Academy","https://portswigger.net/web-security"]],quiz:[["Для ручного повторения и изменения запроса удобен…","Repeater",["Repeater","Proxy только","Dashboard","Decoder только"]]]},
{title:"Injection",track:"Web Security",icon:"💉",desc:"SQLi, command injection, SSRF и XXE — причины и защита.",theory:["Injection возникает, когда данные смешиваются с командами/запросами интерпретатора.","SQL injection защищается параметризованными запросами; command injection — отказом от shell и строгой обработкой аргументов.","SSRF заставляет сервер делать запросы от своего имени; защита включает allowlist, network egress controls и проверку URL.","XXE связан с небезопасной обработкой XML; безопаснее отключать внешние сущности там, где они не нужны."],practice:["Пройти SQLi lab в PortSwigger","Сделать безопасную parameterized query","Разобрать SSRF threat model в локальной лаборатории","Составить injection prevention checklist"],resources:[["OWASP Injection Prevention","https://cheatsheetseries.owasp.org/cheatsheets/Injection_Prevention_Cheat_Sheet.html"],["PortSwigger SQL injection","https://portswigger.net/web-security/sql-injection"],["PortSwigger SSRF","https://portswigger.net/web-security/ssrf"]],quiz:[["Основная идея parameterized query?","Данные отделены от структуры запроса",["Скрыть БД","Данные отделены от структуры запроса","Удалить SQL","Использовать Base64"]]]},
{title:"XSS & browser security",track:"Web Security",icon:"🧩",desc:"Reflected, stored, DOM XSS и CSP.",theory:["XSS — выполнение нежелательного JavaScript в контексте доверенного origin.","Reflected приходит через request и отражается в response; stored сохраняется на сервере; DOM XSS возникает в клиентском коде.","Контекст важен: HTML, attribute, URL и JavaScript требуют разных способов безопасного вывода.","Основы защиты: output encoding, safe DOM APIs, sanitization там, где оправдано, CSP как дополнительный слой."],practice:["Пройти XSS labs в PortSwigger","Найти опасные sinks в небольшом demo-приложении","Заменить innerHTML на безопасные API в учебном коде","Добавить базовую CSP и проверить её"],resources:[["OWASP XSS Prevention","https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html"],["PortSwigger XSS","https://portswigger.net/web-security/cross-site-scripting"]],quiz:[["Stored XSS отличается тем, что payload…","сохраняется и отдаётся другим пользователям",["только в DNS","сохраняется и отдаётся другим пользователям","всегда требует SSRF","работает только в Burp"]]]},
{title:"API Security",track:"Web Security",icon:"🔌",desc:"REST, JWT, authorization и rate limiting.",theory:["API — контракт между клиентом и сервером. Security начинается с правильной authentication и object-level authorization.","JWT содержит claims, но сам по себе не делает authorization правильной.","IDOR/BOLA возникает, когда сервер доверяет идентификатору объекта без проверки прав текущего пользователя.","Rate limiting снижает abuse; schema validation ограничивает неожиданные данные."],practice:["Собрать маленький REST API","Проверить object-level authorization двумя ролями","Разобрать JWT header/payload/signature","Добавить rate limit и validation"],resources:[["OWASP API Security Top 10","https://owasp.org/API-Security/"],["OWASP JWT Cheat Sheet","https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html"]],quiz:[["BOLA/IDOR — это прежде всего проблема…","проверки прав на объект",["DNS","проверки прав на объект","шифрования диска","Git"]]]},
{title:"Windows pentest",track:"Enterprise / Pentest",icon:"🪟",desc:"Enumeration, AD basics и attack paths в лаборатории.",theory:["Pentest начинается с scope, разрешения и цели, а не с запуска инструментов.","Enumeration — сбор информации о хостах, сервисах, пользователях и конфигурации.","Учись строить attack path из подтверждённых фактов, а не из предположений.","Для ИБ полезно уметь не только находить проблему, но и объяснять remediation."],practice:["Развернуть Windows VM в изолированной сети","Собрать локальную инвентаризацию служб","Составить attack surface map своей лаборатории","Описать 3 finding с риском и remediation"],resources:[["Microsoft Learn — Windows security","https://learn.microsoft.com/windows/security/"],["MITRE ATT&CK — Windows","https://attack.mitre.org/"]],quiz:[["Что должно быть до активного тестирования?","Разрешённый scope",["Разрешённый scope","Скан интернета","Пароль администратора","Публичный IP"]]]},
{title:"Active Directory",track:"Enterprise / Pentest",icon:"🏢",desc:"Domains, Kerberos, LDAP, GPO и группы.",theory:["AD — каталог и система управления идентичностями/ресурсами в Windows-домене.","Понимай Domain Controller, users, groups, computers, OU и GPO.","Kerberos используется для сетевой аутентификации в домене; LDAP — протокол доступа к каталогу.","Безопасность AD строится вокруг least privilege, tiering, защищённых админских путей и мониторинга."],practice:["Создать учебный AD в изолированной VM-сети","Изучить структуру OU/groups","Посмотреть Kerberos и LDAP на уровне концепций","Составить AD hardening checklist"],resources:[["Microsoft Learn — Active Directory Domain Services","https://learn.microsoft.com/windows-server/identity/ad-ds/"],["MITRE ATT&CK — Enterprise","https://attack.mitre.org/"]],quiz:[["Kerberos — это прежде всего…","протокол сетевой аутентификации",["файловая система","протокол сетевой аутентификации","SIEM","архиватор"]]]},
{title:"Linux pentest",track:"Enterprise / Pentest",icon:"🐧",desc:"Enumeration, privilege escalation и services.",theory:["Linux security testing начинается с инвентаризации: users, groups, services, files, permissions, network.","Privilege escalation часто появляется из-за неправильных прав, небезопасных сервисов или секретов.","Не копируй команды из случайных write-up вслепую; сначала пойми, что делает команда.","Практикуйся в CTF/лабораториях и фиксируй доказательства."],practice:["Пройти OverTheWire Bandit","Разобрать Linux privilege escalation в учебной VM","Найти misconfiguration и исправить её","Сделать write-up с root cause и remediation"],resources:[["OverTheWire Bandit","https://overthewire.org/wargames/bandit/"],["GTFOBins — use only in labs","https://gtfobins.github.io/"],["MITRE ATT&CK — Linux","https://attack.mitre.org/"]],quiz:[["Enumeration нужна прежде всего для…","понимания attack surface",["случайного запуска exploit","понимания attack surface","шифрования","создания пользователя"]]]},
{title:"Logs & SIEM",track:"Blue Team / SOC",icon:"📊",desc:"Windows/Linux logs, parsing и alerting.",theory:["Логи — источник evidence. SOC связывает события, контекст пользователя, хоста, времени и сети.","SIEM собирает, нормализует и коррелирует события; detection rule превращает паттерн в сигнал.","Изучи Windows Security Event Log, Sysmon и Linux auth/system logs на базовом уровне.","Хороший alert отвечает: что произошло, где, когда, с кем и почему это подозрительно."],practice:["Собрать Windows/Linux логи в лаборатории","Написать простое правило для нескольких failed logins","Сделать timeline одного учебного инцидента","Разобрать false positive и улучшить rule"],resources:[["Microsoft Sysmon","https://learn.microsoft.com/sysinternals/downloads/sysmon"],["Elastic Security documentation","https://www.elastic.co/guide/en/security/current/index.html"],["Splunk Security Essentials","https://splunkbase.splunk.com/app/3435"]],quiz:[["Главная задача detection rule?","Выделить подозрительный паттерн",["Сохранить пароль","Выделить подозрительный паттерн","Запустить exploit","Обновить Windows"]]]},
{title:"MITRE ATT&CK",track:"Blue Team / SOC",icon:"🗺️",desc:"Тактики, техники и mapping detections.",theory:["MITRE ATT&CK описывает поведение adversary через tactics и techniques.","Тактика отвечает на вопрос «зачем», техника — «как».","ATT&CK полезен для threat-informed defense: связывай telemetry, detections и gaps с техниками.","Не путай ATT&CK с каталогом CVE или списком инструментов."],practice:["Выбрать учебный incident и промапить 5 техник","Для каждой техники определить telemetry source","Создать detection idea","Составить gap list для SOC"],resources:[["MITRE ATT&CK","https://attack.mitre.org/"],["MITRE ATT&CK Navigator","https://mitre-attack.github.io/attack-navigator/"]],quiz:[["В ATT&CK tactic описывает…","цель/зачем действия adversary",["конкретный CVE","цель/зачем действия adversary","пароль","IP"]]]},
{title:"Incident Response",track:"Blue Team / SOC",icon:"🚨",desc:"Triage, containment, eradication и recovery.",theory:["Incident response — управляемый процесс от обнаружения до восстановления и lessons learned.","Triage определяет scope и приоритет. Containment ограничивает ущерб. Eradication устраняет причину. Recovery возвращает систему к нормальной работе.","Не уничтожай evidence без необходимости. Фиксируй время, действия и решения.","После инцидента улучшай controls и detections."],practice:["Смоделировать phishing incident","Провести triage по журналам","Составить containment plan","Написать post-incident report"],resources:[["NIST SP 800-61","https://csrc.nist.gov/publications/detail/sp/800-61/rev-2/final"],["CISA Incident Response","https://www.cisa.gov/topics/cyber-threats-and-advisories"]],quiz:[["Containment нужен, чтобы…","ограничить распространение/ущерб",["удалить evidence","ограничить распространение/ущерб","написать CVE","создать аккаунт"]]]},
{title:"CTF foundations",track:"CTF & Portfolio",icon:"🚩",desc:"Recon, web, crypto, forensics и pwn basics.",theory:["CTF — безопасная среда для практики. Начни с понимания задачи и scope.","Recon — поиск информации; web — HTTP и уязвимости; crypto — основы криптографии; forensics — анализ evidence; pwn — memory/exploitation.","Не гонись за количеством flags: write-up и понимание важнее."],practice:["Пройти Bandit","Решить несколько beginner web labs","Сделать простой forensics challenge","Опубликовать write-up без секретов"],resources:[["OverTheWire","https://overthewire.org/wargames/"],["picoCTF","https://picoctf.org/"],["PortSwigger Academy","https://portswigger.net/web-security"]],quiz:[["Что обязательно должно быть у CTF-практики?","Разрешённая учебная среда",["Разрешённая учебная среда","Чужой сервер","Публичный аккаунт","Production"]]]},
{title:"Portfolio project",track:"CTF & Portfolio",icon:"💼",desc:"Лаборатория, write-up, GitHub и документация.",theory:["Портфолио должно показывать процесс: цель, архитектуру, методику, findings, remediation и выводы.","Один хорошо оформленный проект ценнее десяти пустых репозиториев.","Никогда не публикуй реальные токены, персональные данные или результаты тестов без разрешения."],practice:["Создать security lab diagram","Оформить README","Добавить automation script","Написать профессиональный write-up"],resources:[["GitHub Docs","https://docs.github.com/"],["OWASP Cheat Sheet Series","https://cheatsheetseries.owasp.org/"]],quiz:[["Что важнее всего в security portfolio?","Доказуемые навыки и понятная документация",["Количество репозиториев","Доказуемые навыки и понятная документация","Количество подписчиков","Скрытый exploit"]]]},
{title:"Final lab",track:"CTF & Portfolio",icon:"🏆",desc:"End-to-end assessment и финальный отчёт.",theory:["Финальная лаборатория объединяет Linux, сети, web, IAM, detection и отчётность.","Работай по заранее определённому scope. Веди журнал действий и доказательств.","Финальный отчёт: executive summary, scope, methodology, findings, evidence, risk, remediation, limitations.","После lab составь список пробелов и новый цикл обучения."],practice:["Развернуть изолированную лабораторию","Провести assessment по scope","Собрать evidence","Сделать финальный отчёт и remediation plan"],resources:[["NIST Cybersecurity Framework","https://www.nist.gov/cyberframework"],["OWASP Testing Guide","https://owasp.org/www-project-web-security-testing-guide/"],["MITRE ATT&CK","https://attack.mitre.org/"]],quiz:[["Финальный отчёт должен содержать…","scope, findings, evidence и remediation",["Только screenshot","scope, findings, evidence и remediation","Только CVE","Только команды"]]]}
];

const defaultState={done:{},notes:[],xp:0,streak:0,lastStudy:null,view:"home",daily:0,quiz:{},lessonChecks:{},cloud:false};
let state=JSON.parse(localStorage.getItem("cyberroadmap_state_v2")||"null")||defaultState;
state={...defaultState,...state,done:state.done||{},notes:state.notes||{},quiz:state.quiz||{},lessonChecks:state.lessonChecks||{}};

const saveLocal=()=>localStorage.setItem("cyberroadmap_state_v2",JSON.stringify(state));
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(s){const e=document.getElementById("toast");e.textContent=s;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),1800)}
function todayKey(){return new Date().toISOString().slice(0,10)}
function updateStreak(){const t=todayKey();if(state.lastStudy===t)return;if(!state.lastStudy){state.streak=1}else{const a=new Date(state.lastStudy),b=new Date(t);const d=Math.round((b-a)/86400000);state.streak=d===1?state.streak+1:1}state.lastStudy=t}
function totalDone(){return Object.values(state.done).filter(Boolean).length}
function xp(){return Object.entries(state.done).reduce((n,[id,v])=>{if(!v)return n;const [li,ti]=id.split(":").map(Number);return n+(10+ti*5)+(state.quiz[id]||0)},0)}
function level(){return Math.min(50,Math.floor(xp()/100)+1)}
function pct(){return Math.round(totalDone()/ (lessons.length*4) *100)}
function lessonProgress(i){return [0,1,2,3].filter(j=>state.done[`${i}:${j}`]).length}
function go(v){state.view=v;saveLocal();render();window.scrollTo({top:0,behavior:"smooth"})}

async function syncCloud(){
  if(!TG?.initData)return;
  try{
    const r=await fetch(SYNC_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData:TG.initData,action:"sync",progress:state})});
    const data=await r.json();
    if(data.ok){
      state.cloud=true;
      if(data.progress && !state.__localNewer){state={...state,...data.progress,cloud:true}}
      saveLocal();
    }
  }catch(e){console.warn("cloud sync",e)}
}
let syncTimer;
function save(){updateStreak();saveLocal();clearTimeout(syncTimer);syncTimer=setTimeout(syncCloud,350)}

function home(){
  const p=pct(), l=level(), next=lessons.findIndex((_,i)=>lessonProgress(i)<4);
  const completedLessons=lessons.filter((_,i)=>lessonProgress(i)===4).length;
  return `<div class="grid">
    <section class="hero"><div class="eyebrow">PERSONAL CYBERSECURITY OS</div><h1>${p?`Продолжаем путь.`:`Добро пожаловать.`}</h1>
    <p class="muted">Учись как в Duolingo: короткие уроки → практика → мини-тест → XP → уровень. Внутри уже есть теория, лаборатории и проверенные ресурсы.</p>
    <div class="actions"><button class="btn" onclick="openLesson(${next<0?0:next})">${next<0?"🏆 Повторить финал":"▶ Продолжить"}</button><button class="btn secondary" onclick="go('learn')">Открыть курс</button></div></section>
    <section class="card"><div class="eyebrow">ПРОГРЕСС</div><div class="progress-ring">${p}%</div><div class="muted">${completedLessons}/${lessons.length} модулей полностью</div><div class="bar" style="margin:14px 0"><i style="width:${p}%"></i></div><strong>Level ${l}</strong><div class="muted small">${xp()} XP · ещё ${l*100-xp()} XP до следующего уровня</div></section>
  </div>
  <div class="stats" style="margin-top:12px">
    <div class="card stat">🔥<strong>${state.streak}</strong><span>дней streak</span></div>
    <div class="card stat">⚡<strong>${xp()}</strong><span>XP</span></div>
    <div class="card stat">🧪<strong>${totalDone()}</strong><span>этапов</span></div>
    <div class="card stat">📝<strong>${state.notes.length}</strong><span>заметок</span></div>
  </div>
  <div class="section-title"><h2>Сегодняшняя цель</h2><span>20–40 минут</span></div>
  <section class="card daily"><div class="row"><div><strong>Один маленький шаг</strong><div class="muted small">Пройди хотя бы один этап урока сегодня.</div></div><button class="btn" onclick="openLesson(${next<0?0:next})">Начать</button></div></section>
  <div class="section-title"><h2>Направления</h2><span>6 треков</span></div>${trackCards()}`;
}
function trackCards(){
  const map={};
  lessons.forEach((l,i)=>{map[l.track]??=[];map[l.track].push(i)});
  return `<div class="track-grid">${Object.entries(map).map(([t,ids])=>{const d=ids.reduce((n,i)=>n+lessonProgress(i),0),tot=ids.length*4;return `<section class="card track"><div class="track-head"><div class="track-name">${t}</div><span class="tag">${d}/${tot}</span></div><div class="track-desc">${ids.map(i=>lessons[i].title).slice(0,3).join(" · ")}${ids.length>3?" …":""}</div><div class="bar"><i style="width:${d/tot*100}%"></i></div></section>`}).join("")}</div>`
}
function learn(){
 return `<div class="section-title"><h2>Учиться</h2><span>${lessons.length} модулей</span></div>
 <input class="search" id="courseSearch" placeholder="Поиск: Linux, Web, SOC, Python…" oninput="renderLearn(this.value)">
 <div id="lessonGrid" class="lesson-grid" style="margin-top:12px">${lessonCards("")}</div>`;
}
function lessonCards(q){
 q=(q||"").toLowerCase();
 return lessons.map((l,i)=>({l,i})).filter(x=>(x.l.title+" "+x.l.track+" "+x.l.desc).toLowerCase().includes(q)).map(({l,i})=>{
 const p=lessonProgress(i), locked=i>0&&lessonProgress(i-1)<2;
 return `<section class="card lesson-card ${locked?"locked":""}" onclick="${locked ? "toast('Сначала пройди хотя бы 2 этапа предыдущего модуля')" : `openLesson(${i})`}">
 <div class="row"><div class="lesson-num">${i+1}</div><span class="tag">${p}/4</span></div><div class="row"><h3>${l.icon} ${esc(l.title)}</h3><span>${p===4?"✅":""}</span></div><p>${esc(l.desc)}</p><div class="bar"><i style="width:${p*25}%"></i></div><div class="muted small">${l.track} · ${p===4?"Завершено":"Продолжить урок"}</div></section>`
 }).join("")||`<div class="card">Ничего не найдено.</div>`;
}
function renderLearn(q){document.getElementById("lessonGrid").innerHTML=lessonCards(q)}
function practice(){
 const idx=lessons.findIndex((_,i)=>lessonProgress(i)<4); const l=lessons[idx<0?lessons.length-1:idx];
 return `<div class="section-title"><h2>🧪 Практика</h2><span>Безопасные лаборатории</span></div>
 <section class="card hero"><div class="eyebrow">PRACTICE MODE</div><h1>${l.icon} ${esc(l.title)}</h1><p class="muted">Практикуйся только в своих системах или в явно разрешённых учебных лабораториях.</p><div class="actions"><button class="btn" onclick="openLesson(${idx<0?lessons.length-1:idx})">Открыть практику</button><button class="btn secondary" onclick="go('learn')">Выбрать модуль</button></div></section>
 <div class="section-title"><h2>Полезные площадки</h2></div><div class="lesson-grid">
 ${[["PortSwigger Academy","Web Security Labs","https://portswigger.net/web-security"],["OverTheWire","Bandit и другие Wargames","https://overthewire.org/wargames/"],["picoCTF","Beginner CTF","https://picoctf.org/"],["MITRE ATT&CK","Threat-informed defense","https://attack.mitre.org/"]].map(x=>`<a class="card resource" href="${x[2]}" target="_blank" rel="noopener"><strong>${x[0]}</strong><div class="muted small">${x[1]}</div></a>`).join("")}</div>`;
}
function notes(){
 return `<div class="section-title"><h2>📝 Заметки</h2><span>${state.notes.length} сохранено</span></div>
 <section class="card"><input class="search" id="noteTitle" placeholder="Название"><textarea id="noteBody" class="search" style="margin-top:8px;min-height:130px" placeholder="Команды, выводы, вопросы, ссылки…"></textarea><div class="actions"><button class="btn" onclick="addNote()">Сохранить</button></div></section>
 <div class="lesson-grid" style="margin-top:12px">${state.notes.map((n,i)=>`<article class="card"><div class="row"><strong>${esc(n.title||"Без названия")}</strong><button class="icon-btn" onclick="deleteNote(${i})">✕</button></div><p class="muted" style="white-space:pre-wrap">${esc(n.body)}</p><small class="muted">${esc(n.date)}</small></article>`).join("")||`<div class="card">Пока пусто.</div>`}</div>`;
}
function profile(){
 const l=level(), badges=[
 ["🔥","Первый день",state.streak>=1],
 ["⚡","100 XP",xp()>=100],
 ["📚","5 модулей",lessons.filter((_,i)=>lessonProgress(i)===4).length>=5],
 ["🧪","10 практик",totalDone()>=10],
 ["🏆","Финал",lessonProgress(25)===4],
 ["📝","Автор",state.notes.length>=5]
 ];
 return `<section class="card profile-head"><div class="avatar">${TG?.initDataUnsafe?.user?.first_name?.[0]||"C"}</div><div><h2 style="margin:0">${esc(TG?.initDataUnsafe?.user?.first_name||"Cyber Student")}</h2><div class="muted">Level ${l} · ${xp()} XP · ${state.cloud?"☁️ Cloud":"💾 Local"}</div></div></section>
 <div class="section-title"><h2>🏅 Достижения</h2></div><div class="ach-grid">${badges.map(b=>`<div class="card achievement ${b[2]?"":"locked"}"><div style="font-size:25px">${b[0]}</div><strong>${b[1]}</strong><div class="muted small">${b[2]?"Получено":"Ещё не получено"}</div></div>`).join("")}</div>
 <div class="section-title"><h2>📊 Статистика</h2></div><div class="stats"><div class="card stat"><strong>${pct()}%</strong><span>общий прогресс</span></div><div class="card stat"><strong>${state.streak}</strong><span>streak</span></div><div class="card stat"><strong>${totalDone()}</strong><span>этапов</span></div><div class="card stat"><strong>${state.notes.length}</strong><span>заметок</span></div></div>`;
}
function render(){
 document.getElementById("streakPill").textContent=`🔥 ${state.streak}`;
 document.getElementById("xpPill").textContent=`⚡ ${xp()} XP`;
 const m=document.getElementById("main");
 m.innerHTML=state.view==="home"?home():state.view==="learn"?learn():state.view==="practice"?practice():state.view==="notes"?notes():profile();
 document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view));
}
function openLesson(i){
 const l=lessons[i], progress=lessonProgress(i);
 let stage=window.__lessonStage??0;
 if(window.__lessonIndex!==i){stage=0;window.__lessonStage=0;window.__lessonIndex=i}
 const stageNames=["Теория","Практика","Ресурсы","Проверка"];
 const body=stage===0?`<div class="lesson-content"><p>${l.theory.map(x=>`<p>${esc(x)}</p>`).join("")}</div>`:
 stage===1?`<div class="lesson-content"><h3>Лабораторная часть</h3><div class="checklist">${l.practice.map((x,j)=>`<label class="check-row"><input type="checkbox" ${state.lessonChecks[`${i}:${j}`]?"checked":""} onchange="lessonCheck(${i},${j})"><span>${esc(x)}</span></label>`).join("")}</div><p class="muted small" style="margin-top:12px">После выполнения вернись и отметь этап.</p></div>`:
 stage===2?`<div class="lesson-content"><h3>Рекомендуемые ресурсы</h3>${l.resources.map(x=>`<a class="resource" href="${x[1]}" target="_blank" rel="noopener"><strong>${esc(x[0])}</strong><div class="small">${esc(x[1])}</div></a>`).join("")}</div>`:
 `<div class="lesson-content">${l.quiz.map((q,k)=>`<div class="quiz-q"><strong>${esc(q[0])}</strong>${q[2].map(o=>`<button class="option" onclick="answerQuiz(${i},${k},this,'${esc(o)}','${esc(q[1])}')">${esc(o)}</button>`).join("")}<div id="quizmsg${i}_${k}" class="small"></div></div>`).join("")}</div>`;
 const footer=stage<3?`<button class="btn" onclick="completeStage(${i},${stage})">${state.done[`${i}:${stage}`]?"Этап пройден ✓":"Завершить этап"}</button>`:`<button class="btn" onclick="completeStage(${i},3)">Завершить проверку</button>`;
 openModal(`<div class="lesson-modal"><div class="row"><div><div class="eyebrow">${l.track}</div><h2>${l.icon} ${esc(l.title)}</h2><div class="muted small">${progress}/4 этапов</div></div><button class="icon-btn" onclick="closeModal()">✕</button></div><div class="bar" style="margin-top:12px"><i style="width:${progress*25}%"></i></div><div class="lesson-tabs">${stageNames.map((n,j)=>`<button class="tab ${stage===j?"active":""}" onclick="lessonStage(${i},${j})">${j+1}. ${n}${state.done[`${i}:${j}`]?" ✓":""}</button>`).join("")}</div>${body}<div class="actions">${footer}</div></div>`);
}
function lessonStage(i,s){window.__lessonIndex=i;window.__lessonStage=s;openLesson(i)}
function lessonCheck(i,j){state.lessonChecks[`${i}:${j}`]=!state.lessonChecks[`${i}:${j}`];save()}
function completeStage(i,s){if(!state.done[`${i}:${s}`]){state.done[`${i}:${s}`]=true;updateStreak();save();toast(`+${10+s*5} XP · этап завершён`)}else toast("Этап уже завершён");openLesson(i)}
function answerQuiz(i,k,btn,chosen,correct){const key=`${i}:3`;document.querySelectorAll(".option").forEach(b=>b.disabled=true);if(chosen===correct){btn.classList.add("correct");state.quiz[key]=(state.quiz[key]||0)+10;save();document.getElementById(`quizmsg${i}_${k}`).textContent="Верно! +10 XP"}else{btn.classList.add("wrong");document.getElementById(`quizmsg${i}_${k}`).textContent=`Неверно. Правильный ответ: ${correct}`}}
function addNote(){const title=document.getElementById("noteTitle").value.trim(),body=document.getElementById("noteBody").value.trim();if(!body){toast("Добавь текст");return}state.notes.unshift({title,body,date:new Date().toLocaleString("ru-RU")});save();render();toast("Заметка сохранена")}
function deleteNote(i){if(confirm("Удалить заметку?")){state.notes.splice(i,1);save();render()}}
function openSettings(){openModal(`<h2>Настройки</h2><p class="muted">Прогресс хранится локально и синхронизируется с Telegram/Supabase, если облако доступно.</p><div class="actions"><button class="btn ghost" onclick="exportData()">Экспорт JSON</button><button class="btn" onclick="syncCloud().then(()=>toast('Синхронизация выполнена'))">☁️ Синхронизировать</button><button class="btn danger" onclick="resetAll()">Сбросить локальный прогресс</button></div>`)}
function exportData(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="cyberroadmap-progress.json";a.click()}
function resetAll(){if(confirm("Сбросить прогресс на этом устройстве?")){localStorage.removeItem("cyberroadmap_state_v2");state={...defaultState};closeModal();render();toast("Сброшено")}}
function openModal(html){document.getElementById("modalCard").innerHTML=html;document.getElementById("modal").classList.remove("hidden")}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
window.addEventListener("load",async()=>{updateStreak();render();if(TG?.initData){await syncCloud();render()}});
